# CoraBot Configuration Setup
# DO NOT REMOVE THIS FILE!

[discordbot] 
# Bot settings
prefix = "c"
debug = false

[dashboard]
# Dashboard Settings
# Disabled by default, to enable it set the value to true.
enable = false 
# Port for bot dashboard to connect to. default value is 3000 
port = 3000

[private]
# Private settings
# These settings contain tokens or keys used to login or other services. # Do not leak them as others can use your bot user for malicious intent!
token = "TOKEN"
