# CoraBot Configuration Setup
# Required to configure the bot systems.
# DO NOT REMOVE THIS FILE!

[discordbot.general]
# Bot general settings.
# Set the bot's prefix for commands and other options here.
prefix = "p"
# Bot Modules. To enable them, change from false to true.
# Developer only setting! Use this only for debugging the config file.
debug = false

[discordbot.images]
# Image modules settings.
# Client name is used for identifying the bot using some modules.
# If this is left blank, the bot will try to use a temporary name in useragent. 
# This is not recommended as requests from this bot may get blocked by the system.
clientName = "corabot-discord"

[discordbot.automod]
# Bot auto moderation settings
enableAutoMod = false
# This defines which channels are exempt from the moderation function.
whitelistedChannels = ["CHANNEL_ID_HERE"]

[discordbot.dashboard]
# Bot web dashboard interface settings
# Warning! This feature is experimental, use at your own risk.
enableDashboard = false
# Change this if port is in use or unusual things happen.
# Default port for the dashboard is 3000. 
port = 3000

[discordbot.private]
botToken = "TOKEN_HERE"
